In [13]:
import os
import numpy as np
import pandas as pd

from scipy import stats

In [6]:
DATA_DIR = '/Users/rebekahzhang/data/behavior_data'
EXP = "exp2"
DATA_PATH = os.path.join(DATA_DIR, EXP, "trials_training_filtered2.csv")
OUTPUT_DIR = os.path.join(DATA_DIR, f'{EXP}_clustering')
os.makedirs(OUTPUT_DIR, exist_ok=True)

In [7]:
trials = pd.read_csv(DATA_PATH)

In [8]:
trials.head()

,session_trial_num,block_trial_num,block_num,start_time,end_time,bg_drawn,bg_length,bg_repeats,num_bg_licks,miss_trial,...,reward_rate_past_5min_in_block,reward_rate_past_10min_in_block,cumulative_reward,group,dir,mouse,date,time,avg_tw,session
0,0.0,0.0,0.0,1.706626e+09,1.706626e+09,1.2,1.217297,2,1,False,...,0.0,0.0,0.0,s,2024-01-30_09-52-34_RZ034,RZ034,2024-01-30,09-52-34,0.47,0
1,1.0,1.0,0.0,1.706626e+09,1.706626e+09,1.2,7.525090,13,13,False,...,0.0,0.0,0.0,s,2024-01-30_09-52-34_RZ034,RZ034,2024-01-30,09-52-34,0.47,0
2,2.0,2.0,0.0,1.706626e+09,1.706626e+09,1.2,1.299892,2,1,False,...,0.0,0.0,0.0,s,2024-01-30_09-52-34_RZ034,RZ034,2024-01-30,09-52-34,0.47,0
3,3.0,3.0,0.0,1.706626e+09,1.706626e+09,1.0,1.026294,2,1,False,...,0.0,0.0,0.0,s,2024-01-30_09-52-34_RZ034,RZ034,2024-01-30,09-52-34,0.47,0
4,4.0,4.0,0.0,1.706626e+09,1.706626e+09,1.2,1.206799,1,0,False,...,0.0,0.0,0.0,s,2024-01-30_09-52-34_RZ034,RZ034,2024-01-30,09-52-34,0.47,0

In [10]:
trials.keys()

Index(['session_trial_num', 'block_trial_num', 'block_num', 'start_time',
       'end_time', 'bg_drawn', 'bg_length', 'bg_repeats', 'num_bg_licks',
       'miss_trial', 'time_waited', 'time_waited_since_cue_on', 'reward',
       'num_consumption_lick', 'num_pump', 'first_lick', 'last_lick',
       'good_trial', 'time_waited_since_last_lick', 'previous_trial_bg_drawn',
       'previous_trial_bg_length', 'previous_trial_bg_repeats',
       'previous_trial_num_bg_licks', 'previous_trial_first_lick',
       'previous_trial_last_lick', 'previous_trial_time_waited',
       'previous_trial_time_waited_since_cue_on',
       'previous_trial_time_waited_since_last_lick', 'previous_trial_reward',
       'previous_trial_num_consumption_lick', 'previous_trial_miss_trial',
       'bg_length_rolling_mean_5', 'bg_length_rolling_mean_10',
       'bg_repeats_rolling_mean_5', 'bg_repeats_rolling_mean_10',
       'num_bg_licks_rolling_mean_5', 'num_bg_licks_rolling_mean_10',
       'first_lick_rolling_mean_5', 'first_lick_rolling_mean_10',
       'last_lick_rolling_mean_5', 'last_lick_rolling_mean_10',
       'time_waited_rolling_mean_5', 'time_waited_rolling_mean_10',
       'time_waited_since_cue_on_rolling_mean_5',
       'time_waited_since_cue_on_rolling_mean_10',
       'time_waited_since_last_lick_rolling_mean_5',
       'time_waited_since_last_lick_rolling_mean_10', 'reward_rolling_mean_5',
       'reward_rolling_mean_10', 'num_consumption_lick_rolling_mean_5',
       'num_consumption_lick_rolling_mean_10', 'trial_fraction_in_session',
       'trial_fraction_in_block', 'block_fraction_in_session',
       'rewarded_streak', 'unrewarded_streak', 'reward_rate_since_block_start',
       'time_since_last_reward_in_block', 'cumulative_reward_in_block',
       'reward_rate_past_1min_in_block', 'reward_rate_past_5min_in_block',
       'reward_rate_past_10min_in_block', 'cumulative_reward', 'group', 'dir',
       'mouse', 'date', 'time', 'avg_tw', 'session'],
      dtype='object')

In [11]:
trials_non_miss = trials[trials["miss_trial"] == False].copy()

In [12]:
len(trials_non_miss)

598911

In [14]:
tw_short_all = trials_non_miss[trials_non_miss['group'] == 's']["time_waited"].dropna()
tw_long_all = trials_non_miss[trials_non_miss['group'] == 'l']["time_waited"].dropna()
t_stat, p_value = stats.ttest_ind(tw_short_all, tw_long_all)
print(f'{len(trials_non_miss)} all trials')
print(f"S: n={len(tw_short_all)}, mean={tw_short_all.mean():.3f}±{tw_short_all.std():.3f}s")
print(f"L: n={len(tw_long_all)}, mean={tw_long_all.mean():.3f}±{tw_long_all.std():.3f}s")
print(f"T-test: t={t_stat:.3f}, p={p_value}\n")

598911 all trials
S: n=286268, mean=2.030±3.161s
L: n=312643, mean=3.425±5.976s
T-test: t=-111.401, p=0.0

In [15]:
trials_miss = trials[trials["miss_trial"] == True].copy()

In [16]:
trials_miss.head()

,session_trial_num,block_trial_num,block_num,start_time,end_time,bg_drawn,bg_length,bg_repeats,num_bg_licks,miss_trial,...,reward_rate_past_5min_in_block,reward_rate_past_10min_in_block,cumulative_reward,group,dir,mouse,date,time,avg_tw,session
1981,423.0,423.0,0.0,1.706718e+09,1.706718e+09,0.9,0.908102,1,0,True,...,0.383333,0.291667,620.0,s,2024-01-31_10-37-51_RZ034,RZ034,2024-01-31,10-37-51,2.45,1
1982,424.0,424.0,0.0,1.706718e+09,1.706718e+09,1.0,1.006934,1,0,True,...,0.350000,0.283333,620.0,s,2024-01-31_10-37-51_RZ034,RZ034,2024-01-31,10-37-51,2.45,1
1993,435.0,435.0,0.0,1.706718e+09,1.706718e+09,0.9,0.907367,1,0,True,...,0.183333,0.266667,645.0,s,2024-01-31_10-37-51_RZ034,RZ034,2024-01-31,10-37-51,2.45,1
2060,502.0,502.0,0.0,1.706719e+09,1.706719e+09,0.9,0.907505,1,0,True,...,0.250000,0.316667,855.0,s,2024-01-31_10-37-51_RZ034,RZ034,2024-01-31,10-37-51,2.45,1
2230,162.0,162.0,0.0,1.706717e+09,1.706717e+09,0.8,0.806491,1,0,True,...,0.350000,0.291667,380.0,s,2024-01-31_10-39-08_RZ036,RZ036,2024-01-31,10-39-08,4.75,1